version: '3'
services:
  ts-service-test:
    build: .
    image: ts-service-test
    restart: always
    ports:
      - 10101:10101
    volumes:
      - /opt/log/testscript:/opt/log/testscript
    networks:
      - my-network

networks:
  my-network:
    # driver: overlay
    driver: bridge