server:
  port: 10101

cluster:
  host: 10.141.212.146
  port: 31380

k8s:
  address: https://10.141.212.146:6443
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6IiJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJhZG1pbi10b2tlbi1uejg2ZyIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJhZG1pbiIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjhhNDRhZmEzLWY0NzUtMTFlOC1hMTA2LTAwNTA1NmE0Zjk3OCIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDprdWJlLXN5c3RlbTphZG1pbiJ9.OATqVm8smlGZEIfwlD0spK2Kldg4LMmkCNpLa5WPl8n0f5VTYxV5AhISDvAcbyn4mGNBhbP5d4AoUnc7AIoTnf_JXJxD7e8w6Sw_3er0N3O9O9zHt7tGTywO3lM0hZPq64X8AX6_ARVOpZILTdegQPDPIqHborKoBlMtU0LkXrdSusVtyyxcbYaD2h32m4VmGFck4RvtLpahyMK89iFNPf9YHq5e_A3d_Bz9tO-fzIimAo7EEnpwuc8EJVN25uiU-ZSr5mLtJjgLA1BwyDOJnthpOGImq4nd2yIPuMp_xL_5JaJkZkKk4gIHYtMQXAF0IavyhF5oKj0PE_ItBjtIsA

spring:
  datasource:
    url: jdbc:mysql://10.141.212.21:3306/ai_ops
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jooq:
    sql-dialect: org.hibernate.dialect.MySQL5Dialect